### PR TITLE
Upgrade Sylius to dev-master

### PR DESCRIPTION
**Pull request by GSadee**

### CODE REVIEW

**Comment by lchrusciel** [comment]
Do we really need to copy all of migration files?

**Comment by GSadee** [comment]
@lchrusciel And I have the same question, because for now, unfortunately, I do not have any different idea for that 😿

**Comment by lchrusciel** [comment]
For sure we can change migration folder:
```yml
doctrine_migrations:
    dir_name: '%kernel.root_dir%/../vendor/sylius/sylius/app/migration'
    namespace: 'Sylius\Migrations'
```

But I am not sure how could we run them once from this folder

**Comment by michalmarcinkowski** [comment]
@lchrusciel after your change we will no longer be able to add migrations for our application, we can't commit to `/vendor/...`

**Comment by lchrusciel** [comment]
Thats true, but copy pasting migration seems to be not the best solution either... But, there is a hope! We can create a file, lets say `app/config/sylius_migration.yml`
```yml
# app/config/sylius_migration.yml

name: Sylius Migrations
migrations_namespace: Sylius\Migrations
table_name: sylius_migrations
migrations_directory: "vendor/sylius/sylius/app/migrations/"
```

and than, just run migration from this file:
```bash
$ sf d:m:m --configuration app/config/sylius_migration.yml
```
What would you say?

**Pull request closed without merging**
