### PR TITLE
Update build to Symfony 5.2

### PR DESCRIPTION
**Pull request by Tomanhez**

### CODE REVIEW

**Review by arti0090 — APPROVED** [review]

**Review by lchrusciel — COMMENTED** [review]
We should add this to build.yml: 
https://github.com/Sylius/Sylius-Standard/blob/58538de19d670b497d56d3883f95b7c91c337c83/.github/workflows/build.yml#L84-L87

**Review by lchrusciel — COMMENTED** [review]
We need to ensure Symfony version in workflow

**Review by GSadee — APPROVED** [review]

**Review by GSadee — COMMENTED** [review]
You should remove travis configuration to complete the switch to GitHub Actions

**Comment by GSadee** [comment]
Thank you, Tomasz! :1st_place_medal:

**Comment by lchrusciel** [comment]
ouch, didn't notice, that we still lacking this line: https://github.com/Sylius/Plus/blob/master/.github/workflows/build.yml#L77 /cc @Tomanhez

**Pull request merged**
