### PR TITLE
Add link to Swagger UI to info box on homepage

### PR DESCRIPTION
**Pull request by GSadee**
image

### CODE REVIEW

**Comment by lchrusciel** [comment]
Thanks, Grzegorz! :tada:

**Comment by lchrusciel** [comment]
I'm wondering if we even need `is_stable` flag

**Comment by GSadee** [comment]
I've wanted to show this link only on master demo as it is only there available

**Comment by lchrusciel** [comment]
As I mentioned above, this branch will not be deployed as stable in the first place

**Pull request merged**
